"""
VM Stabilizer – LangGraph Multi-Agent Workflow
Flow:
  ServiceNowAgent  ->  PlannerAgent
  ->  CIReachabilityAgent  ->  DiskHealthCheckAgent
  ->  MemoryHealthAgent    ->  CPUHealthCheckAgent
  ->  ProcessCheckAgent
  ->  Human-in-the-Loop
  ->  RestartProcessAgent (approve) | SkipAgent (reject)
"""

import os
import random
import requests
import json
from datetime import datetime
from typing import TypedDict, Literal, Optional
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver
from langgraph.types import interrupt, Command
from langchain_openai import AzureChatOpenAI

# Load Azure OpenAI credentials from .env
load_dotenv()

# Backend API URL
API_URL = "http://localhost:5000"

# Mock VM Service URL – simulates the real Linux VM the agents connect to
MOCK_VM_URL = "http://localhost:3001"

# ─────────────────────────────────────────────
# LLM Setup – Azure OpenAI
# ─────────────────────────────────────────────
def _build_llm() -> Optional[AzureChatOpenAI]:
    """Build the Azure OpenAI chat client. Returns None if creds missing."""
    try:
        return AzureChatOpenAI(
            azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
            api_key=os.getenv("AZURE_OPENAI_API_KEY"),
            api_version=os.getenv("AZURE_OPENAI_API_VERSION"),
            azure_deployment=os.getenv("AZURE_OPENAI_CHAT_DEPLOYMENT_NAME"),
            temperature=0.2,
            timeout=30,
        )
    except Exception as e:
        print(f"  [Warning] LLM init failed: {e}")
        return None

llm = _build_llm()


# ─────────────────────────────────────────────
# Structured Output Schemas (used as LLM tools)
# ─────────────────────────────────────────────
class PlanStep(BaseModel):
    """A single step in the VM remediation plan."""
    step_number: int = Field(description="1-based step index")
    agent: str = Field(description="Name of the agent that runs this step")
    action: str = Field(description="Short imperative action, e.g. 'Ping VM and test SSH port 22'")
    rationale: str = Field(description="Why this step is required for the incident")


class ExecutionPlan(BaseModel):
    """Structured execution plan produced by the PlannerAgent LLM."""
    incident_summary: str = Field(description="One-sentence summary of the incident")
    steps: list[PlanStep] = Field(description="Ordered list of 5-7 diagnostic + remediation steps")
    estimated_risk: Literal["low", "medium", "high"] = Field(
        description="Risk of the proposed remediation to production traffic"
    )


class DiagnosticAnalysis(BaseModel):
    """Structured post-diagnostic analysis produced before human approval."""
    overall_health: Literal["healthy", "degraded", "critical"] = Field(
        description="Overall VM health rollup"
    )
    root_cause: str = Field(description="Most likely root cause of the incident")
    key_findings: list[str] = Field(description="Bullet points summarising each health check")
    recommendation: Literal["restart", "investigate_further", "no_action"] = Field(
        description="Recommended next action for the operator"
    )
    confidence: float = Field(ge=0.0, le=1.0, description="Confidence in the recommendation (0-1)")
    reasoning: str = Field(description="Short justification for the recommendation")


class InvestigationReport(BaseModel):
    """Enterprise ServiceNow-style investigation report composed from workflow findings."""
    incident_summary: str = Field(description="One-paragraph summary of the incident as observed")
    ci_details: list[str] = Field(description="Configuration Item details (host, IP, OS, environment, service offering, etc.)")
    connectivity_findings: list[str] = Field(description="Reachability / SSH / ping observations")
    cpu_findings: list[str] = Field(description="Observed CPU utilization and threshold status")
    memory_findings: list[str] = Field(description="Observed memory utilization and threshold status")
    disk_findings: list[str] = Field(description="Observed filesystem utilization per mount")
    process_findings: list[str] = Field(description="Observed service/process state, PID and active status")
    root_cause_analysis: str = Field(description="Root cause derived strictly from the collected findings")


class AgentNarrative(BaseModel):
    """Enterprise-style investigation narrative generated by LLM."""
    summary: list[str] = Field(description="4-10 concise bullet-point investigation findings")

# ─────────────────────────────────────────────
# Live streaming support (per-request queue)
# ─────────────────────────────────────────────
# When the /run_vm_stabilizer_stream_live endpoint kicks off the workflow,
# it sets a live queue here so log_event() can push events directly to the
# active SSE response instead of relying on an HTTP round-trip.
_live_queue = None

def set_live_queue(q):
    """Register (or clear) the live output queue used by log_event()."""
    global _live_queue
    _live_queue = q

def build_agent_summary(agent_name: str, description: str, output: dict) -> str:
    """
    Generate LLM-driven enterprise investigation narrative for each agent.
    Falls back to static template if LLM is unavailable.
    
    Args:
        agent_name: Name of the agent
        description: Agent task description
        output: Raw JSON output from the agent
    
    Returns:
        Human-readable bullet-point summary (4-10 points)
    """
    # Deterministic agents render directly from collected facts; the LLM tends to
    # collapse structured lists (e.g. per-filesystem bullets) into a single sentence.
    DETERMINISTIC_AGENTS = {
        "ServiceNowAgent", "PlannerAgent", "CIReachabilityAgent",
        "DiskHealthCheckAgent", "MemoryHealthAgent", "CPUHealthCheckAgent",
        "ProcessCheckAgent", "DiagnosticAnalyzerAgent",
        "RestartProcessAgent", "HumanApprovalAgent", "SkipAgent",
    }

    # Try LLM-based narrative generation (kept as a safety net for any future
    # agents not in the deterministic set)
    if llm is not None and agent_name not in DETERMINISTIC_AGENTS:
        try:
            narrative_llm = llm.with_structured_output(AgentNarrative)

            system_prompt = (
                "You are an Enterprise Incident Investigation Reporter. Your purpose is to generate "
                "structured incident investigation findings for each workflow agent.\n\n"
                "CRITICAL INSTRUCTIONS\n"
                "1. Report ONLY facts present in the input.\n"
                "2. DO NOT generate: recommendations, suggestions, future actions, root cause assumptions, "
                "customer impact assumptions, operational guidance, risk analysis, remediation advice, "
                "monitoring advice, or capacity planning comments.\n"
                "3. NEVER use phrases like: should, could, may, might, recommended, advise, risk, impact, "
                "investigate further, consider.\n"
                "4. Every statement must come directly from the supplied data.\n"
                "5. Output ONLY bullet points.\n"
                "6. No introduction, conclusion, or summary paragraph.\n"
                "7. Generate concise investigation findings only.\n"
                "8. Use the exact formatting style shown in the agent-specific rules below. Use '•' for "
                "top-level bullets and indent nested bullets with two spaces before '•'.\n\n"
                "AGENT-SPECIFIC RULES\n"
                "ServiceNowAgent:\n"
                "• Incident ID: <value>\n"
                "• Affected CI: <value>\n"
                "• Short Description: <value>\n"
                "• Description: <value>\n"
                "• Priority: <value>\n"
                "• Created On: <value>\n"
                "• Affected CI Details:\n"
                "  • IP Address: <value>\n"
                "  • Environment: <value>\n"
                "  • Operating System: <value>\n"
                "  • Service Offering: <value>\n"
                "  • Application ID: <value>\n"
                "  • Host: <value>\n"
                "  • Datacenter: <value>\n"
                "Only display CI fields that actually exist in the input data. Do not add "
                "placeholder lines like 'Any additional CI fields available'.\n\n"
                "PlannerAgent:\n"
                "• Total Steps: <count>\n"
                "• Step 1:\n"
                "  • Agent: CIReachabilityAgent\n"
                "  • Action: Verify VM connectivity\n"
                "• Step 2:\n"
                "  • Agent: DiskHealthCheckAgent\n"
                "  • Action: Evaluate filesystem utilization\n"
                "• Step 3:\n"
                "  • Agent: MemoryHealthCheckAgent\n"
                "  • Action: Evaluate system memory usage\n"
                "• Step 4:\n"
                "  • Agent: CPUHealthCheckAgent\n"
                "  • Action: Evaluate CPU utilization\n"
                "• Step 5:\n"
                "  • Agent: ProcessCheckAgent\n"
                "  • Action: Verify service state\n"
                "• Step 6:\n"
                "  • Agent: HumanApprovalAgent\n"
                "  • Action: Operator review of findings\n"
                "• Step 7:\n"
                "  • Agent: RestartProcessAgent\n"
                "  • Action: Restart service if approved\n"
                "Render every step from the provided structured_output.steps list exactly. "
                "Do not generate escalation logic or conditional workflow statements.\n\n"
                "CIReachabilityAgent:\n"
                "• The CIReachabilityAgent completed connectivity validation.\n"
                "• Hostname: <value>\n"
                "• IP Address: <value>\n"
                "• Ping Result: <Success|Failed>\n"
                "• SSH Port 22: <Open|Closed>\n"
                "• Reachability Status: <Reachable|Unreachable>\n\n"
                "DiskHealthCheckAgent: Return ALL filesystem information available.\n"
                "• The DiskHealthCheckAgent has evaluated disk usage across multiple filesystems.\n"
                "• Filesystem: /\n"
                "  • Usage: 41%\n"
                "• Filesystem: /boot\n"
                "  • Usage: 73%\n"
                "• Filesystem: /boot/efi\n"
                "  • Usage: 3%\n"
                "• Filesystem: /opt/new_genai\n"
                "  • Usage: 1%\n"
                "Emit exactly two bullets per filesystem: 'Filesystem: <mount>' and "
                "'Usage: <value>%'. List every discovered filesystem individually. Do not "
                "add extra fields, do not summarize, do not interpret, do not aggregate.\n\n"
                "MemoryHealthAgent:\n"
                "• The MemoryHealthCheckAgent has evaluated system memory usage.\n"
                "• Total Memory Available: <value> MB\n"
                "• Used Memory: <value> MB\n"
                "• Free Memory: <value> MB\n"
                "• Available Memory: <value> MB\n"
                "• Percentage of Free Memory: <value>%\n"
                "• Percentage of Available Memory: <value>%\n\n"
                "CPUHealthCheckAgent:\n"
                "• The CPUHealthCheckAgent has reported the current CPU utilization.\n"
                "• CPU Usage: <value>%\n"
                "• Configured Threshold: <value>%\n"
                "• CPU Operating State: <Normal|Elevated|Critical>\n"
                "• <one-line factual observation based on threshold comparison>\n"
                "Never emit 'pass' / 'fail' / 'warn' / 'Healthy' / 'Warning'. Always map to "
                "Normal / Elevated / Critical.\n\n"
                "ProcessCheckAgent:\n"
                "• The ProcessCheckAgent evaluated service status.\n"
                "• Service Name: <value>\n"
                "• Service State: <value>\n"
                "• Active Status: <value>\n"
                "• PID: <value>\n"
                "• Restart Required: <Yes|No>\n"
                "• Status Message: <value>\n\n"
                "DiagnosticAnalyzerAgent:\n"
                "Incident Investigation Report\n"
                "• Incident Summary: <value>\n"
                "• CI Details:\n"
                "  • <ci detail 1>\n"
                "  • <ci detail 2>\n"
                "• Findings and Observations:\n"
                "  • CPU Utilization:\n"
                "    • <cpu finding>\n"
                "  • Memory Health:\n"
                "    • <memory finding>\n"
                "  • Disk Health:\n"
                "    • <disk finding>\n"
                "  • Process Status:\n"
                "    • <process finding>\n"
                "• Root Cause Analysis: <value>\n"
                "Do NOT include: Resolution Steps, Action Items, Restart Instructions, SSH "
                "Instructions, Operational Procedures, Overall Health, Recommendation, "
                "Confidence, Historical Analysis. Do NOT repeat the same metric across "
                "sections. Total length must not exceed 20 bullets.\n\n"
                "RestartProcessAgent:\n"
                "• The RestartProcessAgent executed the service restart operation.\n"
                "• Service Name: <value>\n"
                "• Previous State: <value>\n"
                "• Current State: <value>\n"
                "• Restart Status: <Success|Failed>\n"
                "• New PID: <value>\n"
                "• Validation Result: Service is operational. (only if Restart Status is Success)\n\n"
                "HumanApprovalAgent:\n"
                "• Approval Status: Approved  (or Rejected)\n\n"
                "SkipAgent:\n"
                "• Action: Restart Skipped\n"
                "• Reason: Operator Rejected\n\n"
                "Output must contain only investigation findings derived from agent execution results."
            )

            user_prompt = (
                "Agent Name:\n"
                f"{agent_name}\n\n"
                "Agent Activity:\n"
                f"{description}\n\n"
                "Agent Output:\n"
                f"{json.dumps(output, indent=2, default=str)}\n\n"
                "Generate the investigation findings for this agent using the exact agent-specific "
                "template. Report only facts from the Agent Output above. Omit any template line whose "
                "value is not present in the Agent Output. Do not add commentary, recommendations, or "
                "impact analysis. Return bullet points only."
            )

            narrative_obj: AgentNarrative = narrative_llm.invoke(
                [{"role": "system", "content": system_prompt},
                 {"role": "user", "content": user_prompt}]
            )

            summary_text = "\n".join([f"• {point}" if not point.lstrip().startswith("•") else point
                                      for point in narrative_obj.summary])
            return summary_text

        except Exception as e:
            print(f"  [Warning] LLM narrative generation failed ({e}); using fallback")
    
    # Fallback: Static template-based summaries
    summary_lines = []

    def _status_label(raw: str, tier: str = "disk") -> str:
        """Map internal status tokens to enterprise labels."""
        r = str(raw).lower()
        if r in ("pass", "ok", "healthy", "success"):
            return "Healthy"
        if r in ("warn", "warning", "degraded"):
            return "Warning"
        if r in ("fail", "failed", "critical", "unhealthy"):
            return "Critical"
        return raw or "Unknown"

    if agent_name == "ServiceNowAgent":
        incident   = output.get("incident_id", "N/A")
        short_desc = output.get("short_description", "N/A")
        desc       = output.get("description", "N/A")
        priority   = output.get("priority", "N/A")
        created    = output.get("created_on", "N/A")
        ci         = output.get("affected_ci", {}) or {}
        ci_name    = ci.get("name") or ci.get("host") or output.get("vm_ip", "N/A")
        summary_lines = [
            f"• Incident ID: {incident}",
            f"• Affected CI: {ci_name}",
            f"• Short Description: {short_desc}",
            f"• Description: {desc}",
            f"• Priority: {priority}",
            f"• Created On: {created}",
            "• Affected CI Details:",
        ]
        ci_fields = [
            ("IP Address",       ci.get("ip_address") or output.get("vm_ip")),
            ("Environment",      ci.get("environment")),
            ("Operating System", ci.get("operating_system")),
            ("Service Offering", ci.get("service_offering")),
            ("Application ID",   ci.get("application_id")),
            ("Host",             ci.get("host")),
            ("Datacenter",       ci.get("datacenter")),
        ]
        for label, value in ci_fields:
            if value not in (None, "", "N/A"):
                summary_lines.append(f"  • {label}: {value}")

    elif agent_name == "PlannerAgent":
        structured = output.get("structured_output", {}) or {}
        steps      = structured.get("steps", []) or []
        total      = output.get("steps", len(steps))
        summary_lines = [f"• Total Steps: {total}"]
        for s in steps:
            summary_lines.append(f"• Step {s.get('step_number', '?')}:")
            summary_lines.append(f"  • Agent: {s.get('agent', 'N/A')}")
            summary_lines.append(f"  • Action: {s.get('action', 'N/A')}")

    elif agent_name == "CIReachabilityAgent":
        hostname   = output.get("hostname", "N/A")
        ip_addr    = output.get("ip_address") or output.get("host", "N/A")
        ping_raw   = str(output.get("ping", "Unknown")).lower()
        ssh_raw    = str(output.get("ssh_port_22", "Unknown")).lower()
        host_stat  = output.get("status", "Unknown")
        ping_disp  = "Success" if ping_raw == "success" else ("Failed" if ping_raw == "fail" else ping_raw.title())
        ssh_disp   = "Open"    if ssh_raw  == "open"    else ("Closed" if ssh_raw  == "closed" else ssh_raw.title())
        reach_disp = "Reachable" if host_stat == "reachable" else "Unreachable"
        summary_lines = [
            "• The CIReachabilityAgent completed connectivity validation.",
            f"• Hostname: {hostname}",
            f"• IP Address: {ip_addr}",
            f"• Ping Result: {ping_disp}",
            f"• SSH Port 22: {ssh_disp}",
            f"• Reachability Status: {reach_disp}",
        ]

    elif agent_name == "DiskHealthCheckAgent":
        filesystems = output.get("filesystems", []) or []
        summary_lines = [
            "• The DiskHealthCheckAgent has evaluated disk usage across multiple filesystems.",
        ]
        if filesystems:
            for fs in filesystems:
                mount = fs.get("mount", "?")
                summary_lines.append(f"• Filesystem: {mount}")
                summary_lines.append(f"  • Usage: {fs.get('used_percent', '?')}%")
        else:
            summary_lines.append(
                f"• Root Filesystem Usage: {output.get('root_usage_percent', 'N/A')}%"
            )

    elif agent_name == "MemoryHealthAgent":
        # Accept both new schema (total_memory_mb) and legacy schema (total_mb) so no
        # matter which shape the caller passed we still render actual values.
        total_mb      = output.get("total_memory_mb",          output.get("total_mb",          "N/A"))
        used_mb       = output.get("used_memory_mb",           output.get("used_mb",           "N/A"))
        free_mb       = output.get("free_memory_mb",           output.get("free_mb",           "N/A"))
        available_mb  = output.get("available_memory_mb",      output.get("available_mb",      "N/A"))
        free_pct      = output.get("free_memory_percent",      output.get("free_percent",      "N/A"))
        available_pct = output.get("available_memory_percent", output.get("available_percent", "N/A"))
        summary_lines = [
            "• The MemoryHealthCheckAgent has evaluated the system memory usage.",
            f"• Total Memory Available: {total_mb} MB",
            f"• Used Memory: {used_mb} MB",
            f"• Free Memory: {free_mb} MB",
            f"• Available Memory: {available_mb} MB",
            f"• Percentage of Free Memory: {free_pct}%",
            f"• Percentage of Available Memory: {available_pct}%",
        ]

    elif agent_name == "CPUHealthCheckAgent":
        cpu_pct   = output.get("cpu_usage_percent", "N/A")
        threshold = output.get("threshold", 85)
        raw_stat  = str(output.get("status", "unknown")).lower()
        if raw_stat in ("pass", "ok", "healthy", "normal"):
            state_disp = "Normal"
        elif raw_stat in ("warn", "warning", "degraded", "elevated"):
            state_disp = "Elevated"
        elif raw_stat in ("fail", "failed", "critical", "unhealthy"):
            state_disp = "Critical"
        else:
            state_disp = raw_stat.title() or "Unknown"
        summary_lines = [
            "• The CPUHealthCheckAgent has reported the current CPU utilization.",
            f"• CPU Usage: {cpu_pct}%",
            f"• Configured Threshold: {threshold}%",
            f"• CPU Operating State: {state_disp}",
        ]
        try:
            if float(cpu_pct) < float(threshold):
                summary_lines.append("• CPU utilization remains below the configured threshold.")
            else:
                summary_lines.append("• CPU utilization has exceeded the configured threshold.")
        except (TypeError, ValueError):
            pass

    elif agent_name == "ProcessCheckAgent":
        service        = output.get("service", "N/A")
        proc_state     = output.get("state", "N/A")
        pid            = output.get("pid", 0)
        needs_restart  = output.get("needs_restart", False)
        active_state   = output.get("active_state", "N/A")
        status_message = output.get("status_message", "")
        summary_lines = [
            "• The ProcessCheckAgent evaluated service status.",
            f"• Service Name: {service}",
            f"• Service State: {proc_state}",
            f"• Active Status: {active_state}",
            f"• PID: {pid}",
            f"• Restart Required: {'Yes' if needs_restart else 'No'}",
        ]
        if status_message:
            summary_lines.append(f"• Status Message: {status_message}")

    elif agent_name == "DiagnosticAnalyzerAgent":
        incident_summary = output.get("incident_summary", "")
        ci_details       = output.get("ci_details", []) or []
        cpu_findings     = output.get("cpu_findings", []) or []
        mem_findings     = output.get("memory_findings", []) or []
        disk_findings    = output.get("disk_findings", []) or []
        proc_findings    = output.get("process_findings", []) or []
        rca              = output.get("root_cause_analysis", output.get("root_cause", "N/A"))

        summary_lines = ["Incident Investigation Report"]
        if incident_summary:
            summary_lines.append(f"• Incident Summary: {incident_summary}")
        if ci_details:
            summary_lines.append("• CI Details:")
            for line in ci_details[:3]:
                summary_lines.append(f"  • {line}")
        summary_lines.append("• Findings and Observations:")
        if cpu_findings:
            summary_lines.append("  • CPU Utilization:")
            for line in cpu_findings:
                summary_lines.append(f"    • {line}")
        if mem_findings:
            summary_lines.append("  • Memory Health:")
            for line in mem_findings:
                summary_lines.append(f"    • {line}")
        if disk_findings:
            summary_lines.append("  • Disk Health:")
            for line in disk_findings:
                summary_lines.append(f"    • {line}")
        if proc_findings:
            summary_lines.append("  • Process Status:")
            for line in proc_findings:
                summary_lines.append(f"    • {line}")
        summary_lines.append(f"• Root Cause Analysis: {rca}")

    elif agent_name == "RestartProcessAgent":
        service   = output.get("service", "N/A")
        raw_stat  = str(output.get("status", "unknown")).lower()
        prev      = output.get("prev_state", "N/A")
        new_state = output.get("new_state", "N/A")
        new_pid   = output.get("new_pid", 0)
        restart_disp = "Success" if raw_stat == "success" else "Failed"
        summary_lines = [
            "• The RestartProcessAgent executed the service restart operation.",
            f"• Service Name: {service}",
            f"• Previous State: {prev}",
            f"• Current State: {new_state}",
            f"• Restart Status: {restart_disp}",
            f"• New PID: {new_pid}",
        ]
        if raw_stat == "success":
            summary_lines.append("• Validation Result: Service is operational.")

    elif agent_name == "HumanApprovalAgent":
        approval = output.get("approval_status", "N/A")
        summary_lines = [f"• Approval Status: {approval}"]

    elif agent_name == "SkipAgent":
        summary_lines = [
            "• Action: Restart Skipped",
            "• Reason: Operator Rejected",
        ]

    # Fallback: if no specific handler matched, render all key-value pairs
    if not summary_lines:
        summary_lines.append(f"• Agent: {agent_name}")
        for key, value in output.items():
            if isinstance(value, (list, dict)):
                summary_lines.append(f"• {key}: {json.dumps(value)[:100]}...")
            else:
                summary_lines.append(f"• {key}: {value}")

    return "\n".join(summary_lines)


def log_event(agent_name: str, task: str, description: str, output: dict, formatted_output: str = "", status: str = "completed"):
    """Log agent event to backend API and (if active) push to live SSE queue.
    
    Args:
        agent_name: Name of the agent
        task: Task description
        description: Detailed description of what the agent did
        output: Raw JSON output dict (kept for backward compatibility and audit)
        formatted_output: Human-readable summary (auto-generated via LLM if empty)
        status: Event status
    """
    # Auto-generate formatted_output via LLM if not provided
    if not formatted_output:
        formatted_output = build_agent_summary(agent_name, description, output)
    print("\n" + "=" * 60)
    print(f"AGENT: {agent_name}")
    print("FORMATTED OUTPUT:")
    print(formatted_output)
    print("=" * 60 + "\n")
    payload = {
        "agent": agent_name,
        "task": task,
        "description": description,
        "output": json.dumps(output) if isinstance(output, dict) else str(output),
        "formatted_output": formatted_output,
        "status": status,
        "timestamp": datetime.now().isoformat()
    }

    # Push to live streaming queue (if a workflow was triggered via the
    # /run_vm_stabilizer_stream_live endpoint)
    if _live_queue is not None:
        try:
            _live_queue.put({"type": "live_output", "content": payload})
        except Exception as e:
            print(f"  [Warning] Failed to push to live queue: {e}")

    # Also POST to the backend event log (keeps /api/agents/event-stream working)
    try:
        requests.post(f"{API_URL}/api/agents/event", json=payload, timeout=5)
    except Exception as e:
        print(f"  [Warning] Failed to log event: {e}")

# ─────────────────────────────────────────────
# Shared State
# ─────────────────────────────────────────────
class VMState(TypedDict):
    vm_ip:             str
    # ServiceNow data
    snow_incident_id:  str
    snow_service:      str    # service reported as stopped/abnormal
    snow_state:        str    # "stopped" or "abnormal"
    # Planner
    plan:              list[str]
    plan_structured:   dict   # ExecutionPlan (LLM structured output)
    # Health checks
    reachable:         bool
    disk_healthy:      bool
    memory_ok:         bool
    cpu_ok:            bool
    # Process check
    process_state:     str    # actual current state found on VM
    process_pid:       int
    # Per-agent raw findings (used by DiagnosticAnalyzerAgent)
    ci_details:            dict
    connectivity_findings: dict
    disk_findings:         dict
    memory_findings:       dict
    cpu_findings:          dict
    process_findings:      dict
    # LLM diagnostic analysis
    diagnosis:         dict   # DiagnosticAnalysis (LLM structured output)
    # Decision
    human_approved:    bool
    report:            list[str]


# ─────────────────────────────────────────────
# Agent 1 – ServiceNowAgent
# ─────────────────────────────────────────────
def agent_servicenow(state: VMState) -> VMState:
    print("\n[ServiceNowAgent] Fetching incident details from ServiceNow...")

    try:
        # Fetch from backend API
        response = requests.get(f"{API_URL}/api/servicenow/incidents", timeout=5)
        data = response.json()
        
        if data["identified_tickets"] > 0:
            incident = data["tickets_info"][0]
            msg = (f"Incident: {incident['incident_number']} | VM: {incident['vm_ip']} | "
                   f"Service: '{incident['service_name']}' | State: {incident['state']} | Priority: High")
            print(f"  {msg}")
            
            # Log event
            output_data = {
                "incident_id":       incident['incident_number'],
                "short_description": incident.get('short_description', ''),
                "description":       incident.get('main_description') or incident.get('description', ''),
                "priority":          incident.get('priority', ''),
                "created_on":        incident.get('created_on', ''),
                "affected_ci":       incident.get('affected_ci', {}),
                "vm_ip":             incident['vm_ip'],
                "service":           incident['service_name'],
                "state":             incident['state'],
                "url":               incident.get('url', ''),
            }
            log_event(
                "ServiceNowAgent",
                "Fetch Incident",
                f"Fetching incident {incident['incident_number']} from ServiceNow",
                output_data
            )
            
            return {
                **state,
                "vm_ip":            incident["vm_ip"],
                "snow_incident_id": incident["incident_number"],
                "snow_service":     incident["service_name"],
                "snow_state":       incident["state"],
                "ci_details":       output_data,
                "report":           state["report"] + [f"ServiceNowAgent: {msg}"]
            }
        else:
            print("  [INFO] No incidents found")
            return state
    
    except Exception as e:
        print(f"  [ERROR] Failed to fetch ServiceNow incidents: {e}")
        return state


# ─────────────────────────────────────────────
# Agent 2 – PlannerAgent (LLM + structured output)
# ─────────────────────────────────────────────
def agent_planner(state: VMState) -> VMState:
    print("\n[PlannerAgent] Generating execution plan via Azure OpenAI (structured output)...")

    # Canonical fixed workflow sequence — always emitted so the display matches the graph.
    canonical_steps = [
        {"step_number": 1, "agent": "CIReachabilityAgent",     "action": "Verify VM connectivity"},
        {"step_number": 2, "agent": "DiskHealthCheckAgent",    "action": "Evaluate filesystem utilization"},
        {"step_number": 3, "agent": "MemoryHealthCheckAgent",  "action": "Evaluate system memory usage"},
        {"step_number": 4, "agent": "CPUHealthCheckAgent",     "action": "Evaluate CPU utilization"},
        {"step_number": 5, "agent": "ProcessCheckAgent",       "action": f"Verify state of service '{state['snow_service']}'"},
        {"step_number": 6, "agent": "HumanApprovalAgent",      "action": "Operator review of findings"},
        {"step_number": 7, "agent": "RestartProcessAgent",     "action": f"Restart service '{state['snow_service']}' if approved"},
    ]
    plan_lines = [f"Step {s['step_number']} : {s['agent']} – {s['action']}" for s in canonical_steps]

    plan_structured: dict = {"steps": canonical_steps}

    if llm is not None:
        try:
            planner_llm = llm.with_structured_output(ExecutionPlan)

            system = (
                "You are an SRE planning agent. Produce a one-sentence incident_summary "
                "for the given ServiceNow incident. The workflow steps are fixed and will "
                "be substituted by the caller; still return the canonical 7 steps exactly "
                "as: CIReachabilityAgent, DiskHealthCheckAgent, MemoryHealthCheckAgent, "
                "CPUHealthCheckAgent, ProcessCheckAgent, HumanApprovalAgent, "
                "RestartProcessAgent."
            )
            user = (
                f"Incident: {state['snow_incident_id']}\n"
                f"VM: {state['vm_ip']}\n"
                f"Service: {state['snow_service']}\n"
                f"Reported state: {state['snow_state']}\n"
                "Produce the plan."
            )

            plan_obj: ExecutionPlan = planner_llm.invoke(
                [{"role": "system", "content": system},
                 {"role": "user", "content": user}]
            )
            plan_structured["incident_summary"] = plan_obj.incident_summary
            print(f"  [LLM] Incident summary: {plan_obj.incident_summary}")
        except Exception as e:
            print(f"  [Warning] LLM planner failed, using canonical plan: {e}")

    print("  Execution plan:")
    for step in plan_lines:
        print(f"    {step}")

    output_data = {
        "steps": len(canonical_steps),
        "status": "plan_created",
        "structured_output": plan_structured,
    }
    log_event(
        "PlannerAgent",
        "Generate Execution Plan (LLM)",
        "Generating execution plan via Azure OpenAI (structured output)",
        output_data
    )

    return {
        **state,
        "plan":            plan_lines,
        "plan_structured": plan_structured,
        "report":          state["report"] + [f"PlannerAgent: LLM plan created ({len(plan_lines)} steps)"]
    }


# ─────────────────────────────────────────────
# Agent 3 – CIReachabilityAgent (calls mock VM service)
# ─────────────────────────────────────────────
def agent_ci_reachability(state: VMState) -> VMState:
    print(f"\n[CIReachabilityAgent] Checking reachability of VM {state['vm_ip']}...")

    reachable = False
    ssh_open = False
    ping_out = ""
    ssh_out = ""
    hostname = ""
    try:
        r = requests.post(f"{MOCK_VM_URL}/api/vm/ping", json={"vm_ip": state["vm_ip"]}, timeout=5).json()
        reachable = bool(r.get("success"))
        ping_out = r.get("output", "")
        hostname = r.get("hostname", "") or hostname
        s = requests.post(f"{MOCK_VM_URL}/api/vm/ssh-check", json={"vm_ip": state["vm_ip"]}, timeout=5).json()
        ssh_open = bool(s.get("success"))
        ssh_out = s.get("output", "")
        hostname = hostname or s.get("hostname", "")
    except Exception as e:
        print(f"  [Warning] Mock VM unreachable ({e}); assuming host is up for demo")
        reachable = True
        ssh_open = True

    status = "[OK] VM is reachable (ping + SSH port 22 open)" if (reachable and ssh_open) \
             else "[FAIL] VM not reachable"
    print(f"  {status}")
    if ping_out: print(f"  {ping_out}")
    if ssh_out:  print(f"  {ssh_out}")

    connectivity_data = {
        "hostname": hostname or (state.get("ci_details", {}) or {}).get("affected_ci", {}).get("host", "N/A"),
        "host": state['vm_ip'],
        "ip_address": state['vm_ip'],
        "ping": "success" if reachable else "fail",
        "ssh_port_22": "open" if ssh_open else "closed",
        "status": "reachable" if (reachable and ssh_open) else "unreachable",
    }
    log_event(
        "CIReachabilityAgent",
        "VM Connectivity Diagnostic",
        f"Ping + SSH port 22 check on {state['vm_ip']} via mock VM service",
        connectivity_data
    )

    return {
        **state,
        "reachable": reachable and ssh_open,
        "connectivity_findings": connectivity_data,
        "report":    state["report"] + [f"CIReachabilityAgent: {status}"]
    }


# ─────────────────────────────────────────────
# Agent 4 – DiskHealthCheckAgent (calls mock VM service)
# ─────────────────────────────────────────────
def agent_disk_health(state: VMState) -> VMState:
    print("\n[DiskHealthCheckAgent] Checking disk usage on VM (df -h /)...")

    disk_pct = 0
    disk_healthy = True
    raw_output = ""
    filesystems = []
    try:
        r = requests.get(f"{MOCK_VM_URL}/api/vm/disk", timeout=5).json()
        disk_pct = int(r.get("used_percent", 0))
        disk_healthy = bool(r.get("healthy", disk_pct < 90))
        raw_output = r.get("output", "")
        filesystems = r.get("filesystems", []) or []
    except Exception as e:
        print(f"  [Warning] Mock VM disk endpoint failed ({e}); using fallback")
        disk_pct = random.randint(30, 72)
        disk_healthy = disk_pct < 90

    # Guarantee a filesystem breakdown even if the mock call failed
    if not filesystems:
        filesystems = [
            {"filesystem": "devtmpfs",  "mount": "/dev",           "size_gb": 16,  "used_percent": 0,  "total_blocks": 16515072,  "available_blocks": 16515072},
            {"filesystem": "tmpfs",     "mount": "/dev/shm",       "size_gb": 16,  "used_percent": 1,  "total_blocks": 16515072,  "available_blocks": 16349921},
            {"filesystem": "tmpfs",     "mount": "/run",           "size_gb": 4,   "used_percent": 1,  "total_blocks": 4128768,   "available_blocks": 4087480},
            {"filesystem": "/dev/sda1", "mount": "/",              "size_gb": 100, "used_percent": disk_pct, "total_blocks": 261065728, "available_blocks": 154028780},
            {"filesystem": "/dev/sda2", "mount": "/boot",          "size_gb": 1,   "used_percent": 73, "total_blocks": 999320,    "available_blocks": 269816},
            {"filesystem": "/dev/sda3", "mount": "/boot/efi",      "size_gb": 1,   "used_percent": 3,  "total_blocks": 523248,    "available_blocks": 507564},
            {"filesystem": "/dev/sdb1", "mount": "/opt/new_genai", "size_gb": 200, "used_percent": 1,  "total_blocks": 524288000, "available_blocks": 519045120},
        ]

    status = f"[OK] Disk {disk_pct}% used (threshold 90%)" if disk_healthy else f"[FAIL] Disk {disk_pct}% – Critical"
    print(f"  {status}")
    if raw_output: print(f"  {raw_output}")

    output_data = {
        "root_usage_percent": disk_pct,
        "threshold":          90,
        "status":             "pass" if disk_healthy else "fail",
        "filesystems":        filesystems,
    }
    log_event(
        "DiskHealthCheckAgent",
        "Disk Usage Check",
        "Checking disk usage on VM (df -h)",
        output_data
    )

    return {
        **state,
        "disk_healthy":  disk_healthy,
        "disk_findings": output_data,
        "report":        state["report"] + [f"DiskHealthCheckAgent: {status}"]
    }


# ─────────────────────────────────────────────
# Agent 5 – MemoryHealthAgent (calls mock VM service)
# ─────────────────────────────────────────────
def agent_memory_health(state: VMState) -> VMState:
    print("\n[MemoryHealthAgent] Checking memory usage on VM (free -m)...")

    mem_pct = 0
    memory_ok = True
    raw_output = ""
    mem_details = {}
    try:
        r = requests.get(f"{MOCK_VM_URL}/api/vm/memory", timeout=5).json()
        mem_pct = int(r.get("used_percent", 0))
        memory_ok = bool(r.get("healthy", mem_pct < 90))
        raw_output = r.get("output", "")
        mem_details = {
            "total_memory_mb":          r.get("total_mb"),
            "used_memory_mb":           r.get("used_mb"),
            "free_memory_mb":           r.get("free_mb"),
            "available_memory_mb":      r.get("available_mb"),
            "free_memory_percent":      r.get("free_percent"),
            "available_memory_percent": r.get("available_percent"),
        }
    except Exception as e:
        print(f"  [Warning] Mock VM memory endpoint failed ({e}); using fallback")
        mem_pct = random.randint(40, 75)
        memory_ok = mem_pct < 90

    # Guarantee every memory field has a value even if the mock call failed
    if not mem_details or mem_details.get("total_memory_mb") is None:
        total_mb     = 8192
        used_mb      = int(total_mb * mem_pct / 100)
        free_mb      = total_mb - used_mb
        available_mb = free_mb + 512
        mem_details = {
            "total_memory_mb":          total_mb,
            "used_memory_mb":           used_mb,
            "free_memory_mb":           free_mb,
            "available_memory_mb":      available_mb,
            "free_memory_percent":      round(free_mb * 100 / total_mb, 1),
            "available_memory_percent": round(available_mb * 100 / total_mb, 1),
        }

    status = f"[OK] Memory {mem_pct}% used (threshold 90%)" if memory_ok else f"[FAIL] Memory {mem_pct}% – Critical"
    print(f"  {status}")
    if raw_output: print(f"  {raw_output}")

    output_data = {
        "memory_used_percent": mem_pct,
        "threshold":           90,
        "status":              "pass" if memory_ok else "fail",
        **{k: v for k, v in mem_details.items() if v is not None},
    }
    log_event(
        "MemoryHealthAgent",
        "Memory Usage Check",
        "Checking memory usage on VM (free -m)",
        output_data
    )

    return {
        **state,
        "memory_ok":       memory_ok,
        "memory_findings": output_data,
        "report":          state["report"] + [f"MemoryHealthAgent: {status}"]
    }


# ─────────────────────────────────────────────
# Agent 6 – CPUHealthCheckAgent (calls mock VM service)
# ─────────────────────────────────────────────
def agent_cpu_health(state: VMState) -> VMState:
    print("\n[CPUHealthCheckAgent] Checking CPU load on VM (top -bn1)...")

    cpu_pct = 0.0
    cpu_ok = True
    raw_output = ""
    try:
        r = requests.get(f"{MOCK_VM_URL}/api/vm/cpu", timeout=5).json()
        cpu_pct = float(r.get("load_percent", 0))
        cpu_ok = bool(r.get("healthy", cpu_pct < 85))
        raw_output = r.get("output", "")
    except Exception as e:
        print(f"  [Warning] Mock VM cpu endpoint failed ({e}); using fallback")
        cpu_pct = random.uniform(20, 55)
        cpu_ok = cpu_pct < 85

    status = f"[OK] CPU {cpu_pct:.1f}% (threshold 85%)" if cpu_ok else f"[WARN] CPU {cpu_pct:.1f}% – High load"
    print(f"  {status}")
    if raw_output: print(f"  {raw_output}")

    output_data = {"cpu_usage_percent": round(cpu_pct, 1), "threshold": 85, "status": "pass" if cpu_ok else "warn"}
    log_event(
        "CPUHealthCheckAgent",
        "CPU Load Check",
        "Checking CPU load on VM (top -bn1)",
        output_data
    )

    return {
        **state,
        "cpu_ok":        cpu_ok,
        "cpu_findings":  output_data,
        "report":        state["report"] + [f"CPUHealthCheckAgent: {status}"]
    }


# ─────────────────────────────────────────────
# Agent 7 – ProcessCheckAgent (calls mock VM service)
# ─────────────────────────────────────────────
def agent_process_check(state: VMState) -> VMState:
    service = state["snow_service"]
    print(f"\n[ProcessCheckAgent] systemctl status {service} on VM...")

    process_state   = state["snow_state"]
    pid             = 0
    raw_output      = ""
    active_state    = ""
    service_status  = False
    status_message  = ""
    try:
        r = requests.get(f"{MOCK_VM_URL}/api/vm/service/{service}/status", timeout=5).json()
        if r.get("success"):
            process_state  = r.get("state", process_state)
            pid            = int(r.get("pid", 0))
            raw_output     = r.get("systemctl_output", r.get("output", ""))
            active_state   = r.get("active_state", "")
            service_status = bool(r.get("service_status", process_state == "running"))
            status_message = r.get("status_message", "")
        else:
            print(f"  [Warning] Mock VM reports: {r.get('error', 'unit not found')}")
    except Exception as e:
        print(f"  [Warning] Mock VM service endpoint failed ({e}); using ServiceNow-reported state")
        pid = random.randint(1000, 9999) if process_state == "running" else 0

    # Derive any values the mock didn't provide (fallback path)
    if not active_state:
        active_state = {
            "running":  "active (running)",
            "stopped":  "inactive (dead)",
            "abnormal": "activating (auto-restart)",
        }.get(process_state, process_state)
    if not status_message:
        status_message = (
            f"{service} is running (PID {pid})" if process_state == "running"
            else f"{service} service is not running"
        )
    service_status = service_status or (process_state == "running")

    needs_restart = process_state in ["stopped", "abnormal"]

    if process_state == "stopped":
        status = f"[CONFIRM] '{service}' is STOPPED – needs restart"
    elif process_state == "abnormal":
        status = f"[CONFIRM] '{service}' is in ABNORMAL state (PID {pid}) – needs restart"
    else:
        status = f"[OK] '{service}' is running normally (PID {pid})"

    print(f"  {status}")
    if raw_output: print(f"  {raw_output}")

    output_data = {
        "service":          service,
        "state":            process_state,
        "pid":              pid,
        "needs_restart":    needs_restart,
        "service_status":   service_status,
        "active_state":     active_state,
        "status_message":   status_message,
        "systemctl_output": raw_output,
    }
    log_event(
        "ProcessCheckAgent",
        "Service State Verification",
        f"Checking service status on VM (systemctl status {service})",
        output_data
    )

    return {
        **state,
        "process_state":    process_state,
        "process_pid":      pid,
        "process_findings": output_data,
        "report":           state["report"] + [f"ProcessCheckAgent: {status}"]
    }


# ─────────────────────────────────────────────
# Agent 7b – DiagnosticAnalyzerAgent (LLM + structured output)
# ─────────────────────────────────────────────
def agent_diagnostic_analyzer(state: VMState) -> VMState:
    print("\n[DiagnosticAnalyzerAgent] Composing investigation report via Azure OpenAI (structured output)...")

    ci      = state.get("ci_details", {}) or {}
    conn    = state.get("connectivity_findings", {}) or {}
    disk_f  = state.get("disk_findings", {}) or {}
    mem_f   = state.get("memory_findings", {}) or {}
    cpu_f   = state.get("cpu_findings", {}) or {}
    proc_f  = state.get("process_findings", {}) or {}

    affected_ci = ci.get("affected_ci", {}) or {}
    fs_list     = disk_f.get("filesystems", []) or []

    # Rule-based investigation report (also used as LLM fallback)
    overall_health = "critical" if state["process_state"] in ("stopped", "abnormal") else (
        "degraded" if not (state["reachable"] and state["disk_healthy"] and state["memory_ok"] and state["cpu_ok"]) else "healthy"
    )
    recommendation = "restart" if state["process_state"] in ("stopped", "abnormal") else (
        "investigate_further" if overall_health == "degraded" else "no_action"
    )

    ci_lines = [
        f"Host: {affected_ci.get('host', 'N/A')} ({affected_ci.get('ip_address', state['vm_ip'])})",
        f"Environment: {affected_ci.get('environment', 'N/A')} | OS: {affected_ci.get('operating_system', 'N/A')}",
        f"Service Offering: {affected_ci.get('service_offering', 'N/A')} | Application: {affected_ci.get('application_id', 'N/A')}",
        f"Datacenter: {affected_ci.get('datacenter', 'N/A')}",
        f"Incident: {ci.get('incident_number', state['snow_incident_id'])} | Priority: {ci.get('priority', 'N/A')}",
    ]

    connectivity_lines = [
        f"Ping to {conn.get('host', state['vm_ip'])}: {conn.get('ping', 'unknown')}",
        f"SSH port 22: {conn.get('ssh_port_22', 'unknown')}",
        f"Overall connectivity: {conn.get('status', 'reachable' if state['reachable'] else 'unreachable')}",
    ]

    def _label(raw: str, healthy_flag: bool) -> str:
        r = str(raw).lower()
        if r in ("pass", "ok", "healthy"): return "Healthy"
        if r in ("warn", "warning", "degraded"): return "Warning"
        if r in ("fail", "failed", "critical", "unhealthy"): return "Critical"
        return "Healthy" if healthy_flag else "Critical"

    cpu_lines = [
        f"CPU Usage: {cpu_f.get('cpu_usage_percent', 'N/A')}%",
        f"CPU Operating State: {_label(cpu_f.get('status'), state['cpu_ok']).replace('Healthy', 'Normal').replace('Warning', 'Elevated')}",
    ]

    memory_lines = [
        f"Total Memory: {mem_f.get('total_memory_mb', mem_f.get('total_mb', 'N/A'))} MB",
        f"Used Memory: {mem_f.get('used_memory_mb', mem_f.get('used_mb', 'N/A'))} MB",
        f"Free Memory: {mem_f.get('free_memory_mb', mem_f.get('free_mb', 'N/A'))} MB",
        f"Available Memory: {mem_f.get('available_memory_mb', mem_f.get('available_mb', 'N/A'))} MB",
    ]

    if fs_list:
        disk_lines = ["Filesystems Evaluated:"] + [
            f"  {fs.get('mount', '?')} = {fs.get('used_percent', '?')}%" for fs in fs_list
        ]
    else:
        disk_lines = [
            f"Root Filesystem Usage: {disk_f.get('root_usage_percent', 'N/A')}%"
        ]

    process_lines = [
        f"Service Name: {proc_f.get('service', state['snow_service'])}",
        f"Service State: {proc_f.get('state', state['process_state'])}",
        f"PID: {proc_f.get('pid', state['process_pid'])}",
    ]

    if state["process_state"] in ("stopped", "abnormal"):
        rca = (
            f"Service '{state['snow_service']}' is reported as '{state['process_state']}' on host "
            f"{affected_ci.get('host', state['vm_ip'])} (PID {state['process_pid']}). "
            f"Infrastructure metrics (CPU {cpu_f.get('cpu_usage_percent', 'N/A')}%, "
            f"Memory {mem_f.get('memory_used_percent', 'N/A')}%, "
            f"Disk {disk_f.get('root_usage_percent', 'N/A')}%) do not exceed thresholds, "
            f"indicating a service-level failure rather than a resource exhaustion event."
        )
    else:
        rca = "No critical service or resource issue detected; all health checks within thresholds."

    fallback_report = {
        "incident_summary": (
            f"Incident {state['snow_incident_id']} on VM {state['vm_ip']} reports service "
            f"'{state['snow_service']}' in state '{state['snow_state']}'. Actual observed state on host: "
            f"'{state['process_state']}'."
        ),
        "ci_details":            ci_lines,
        "connectivity_findings": connectivity_lines,
        "cpu_findings":          cpu_lines,
        "memory_findings":       memory_lines,
        "disk_findings":         disk_lines,
        "process_findings":      process_lines,
        "root_cause_analysis":   rca,
    }

    diagnosis: dict = fallback_report

    if llm is not None:
        try:
            analyzer_llm = llm.with_structured_output(InvestigationReport)

            system = (
                "You are an Enterprise Incident Investigation Analyst producing a ServiceNow-style "
                "investigation report. You MUST base every statement strictly on the workflow data "
                "provided below. Do NOT invent metrics, hostnames, IPs, PIDs, or thresholds. "
                "Do NOT produce generic advice, resolution steps, or action items. Every finding and "
                "root cause statement must cite concrete values from the provided data (percentages, "
                "MB values, filesystem mounts, service name, PID, active state, environment, OS, etc.). "
                "If a datum is missing, state 'N/A' rather than fabricating a value. "
                "Do not repeat the same metric across sections."
            )
            user = (
                "Compose an investigation report using ONLY the following collected workflow data.\n\n"
                f"=== ServiceNow Ticket / CI Details ===\n{json.dumps(ci, indent=2, default=str)}\n\n"
                f"=== Connectivity Findings (CIReachabilityAgent) ===\n{json.dumps(conn, indent=2, default=str)}\n\n"
                f"=== Disk Findings (DiskHealthCheckAgent) ===\n{json.dumps(disk_f, indent=2, default=str)}\n\n"
                f"=== Memory Findings (MemoryHealthCheckAgent) ===\n{json.dumps(mem_f, indent=2, default=str)}\n\n"
                f"=== CPU Findings (CPUHealthCheckAgent) ===\n{json.dumps(cpu_f, indent=2, default=str)}\n\n"
                f"=== Process Findings (ProcessCheckAgent) ===\n{json.dumps(proc_f, indent=2, default=str)}\n\n"
                f"=== Observed State Summary ===\n"
                f"reachable={state['reachable']}, disk_healthy={state['disk_healthy']}, "
                f"memory_ok={state['memory_ok']}, cpu_ok={state['cpu_ok']}, "
                f"process_state='{state['process_state']}', process_pid={state['process_pid']}\n\n"
                "Populate every section of the InvestigationReport schema with facts from the data above."
            )

            report_obj: InvestigationReport = analyzer_llm.invoke(
                [{"role": "system", "content": system},
                 {"role": "user", "content": user}]
            )
            diagnosis = report_obj.model_dump()
        except Exception as e:
            print(f"  [Warning] LLM analyzer failed, using rule-based report: {e}")

    print(f"  Root cause     : {diagnosis.get('root_cause_analysis', 'N/A')}")

    log_event(
        "DiagnosticAnalyzerAgent",
        "Incident Investigation Report",
        "Composing enterprise investigation report from collected agent findings",
        diagnosis
    )

    return {
        **state,
        "diagnosis": diagnosis,
        "report":    state["report"] + [
            f"DiagnosticAnalyzerAgent: investigation report generated ({overall_health})"
        ]
    }


# ─────────────────────────────────────────────
# Agent 8 – Human-in-the-Loop Approval
# ─────────────────────────────────────────────
def agent_human_approval(state: VMState) -> VMState:
    print("\n" + "=" * 56)
    print("  HEALTH CHECK SUMMARY")
    print("=" * 56)
    for line in state["report"]:
        print(f"  {line}")
    print("=" * 56)
    print(f"\n  Incident       : {state['snow_incident_id']}")
    print(f"  Service        : {state['snow_service']}")
    print(f"  Current State  : {state['process_state'].upper()}")
    print(f"  Proposed Action: Restart '{state['snow_service']}' on {state['vm_ip']}")
    diag = state.get("diagnosis") or {}
    if diag.get("root_cause_analysis"):
        print(f"  Root Cause     : {diag['root_cause_analysis']}")
    print("=" * 56)

    # LangGraph interrupt – graph pauses here until human responds
    decision = interrupt({
        "message": (f"Restart service '{state['snow_service']}' "
                    f"(currently {state['process_state']}) on {state['vm_ip']}?"),
        "options": ["approve", "reject"]
    })

    # Graph resumes here with the human's decision – no re-print of summary
    approved = str(decision).strip().lower() == "approve"
    result = "[APPROVED]" if approved else "[REJECTED]"
    print(f"\n  Human decision : {result}")

    log_event(
        "HumanApprovalAgent",
        "Operator Approval Decision",
        "Operator review of proposed remediation",
        {"approval_status": "Approved" if approved else "Rejected"}
    )

    return {
        **state,
        "human_approved": approved,
        "report":         state["report"] + [f"Human Approval: {result}"]
    }


# ─────────────────────────────────────────────
# Agent 9a – RestartProcessAgent (calls mock VM service)
# ─────────────────────────────────────────────
def agent_restart_process(state: VMState) -> VMState:
    service = state["snow_service"]
    print(f"\n[RestartProcessAgent] systemctl restart {service} on VM {state['vm_ip']}...")

    success = False
    new_pid = 0
    prev_state = state["process_state"]
    raw_output = ""
    try:
        r = requests.post(f"{MOCK_VM_URL}/api/vm/service/{service}/restart", timeout=10).json()
        success = bool(r.get("success"))
        new_pid = int(r.get("pid", 0))
        raw_output = r.get("output", "")
    except Exception as e:
        print(f"  [Warning] Mock VM restart endpoint failed ({e}); simulating success")
        success = True
        new_pid = random.randint(1000, 9999)

    if success:
        msg = f"[DONE] Service '{service}' restarted successfully. New state: running (PID {new_pid})."
    else:
        msg = f"[FAIL] Failed to restart '{service}'"
    print(f"  {msg}")
    if raw_output: print(f"  {raw_output}")

    output_data = {
        "service":    service,
        "action":     "restart",
        "prev_state": prev_state,
        "new_state":  "running" if success else prev_state,
        "new_pid":    new_pid,
        "status":     "success" if success else "fail",
    }
    log_event(
        "RestartProcessAgent",
        "Service Restart",
        "Restarting service on VM via mock service",
        output_data
    )

    return {
        **state,
        "process_state": "running" if success else prev_state,
        "process_pid":   new_pid if success else state["process_pid"],
        "report":        state["report"] + [f"RestartProcessAgent: {msg}"]
    }


# ─────────────────────────────────────────────
# Agent 9b – SkipAgent
# ─────────────────────────────────────────────
def agent_skip(state: VMState) -> VMState:
    msg = "[INFO] Restart skipped – rejected by operator. No changes made to VM."
    print(f"\n  {msg}")
    output_data = {"status": "skipped", "reason": "operator_rejected", "message": msg}
    log_event(
        "SkipAgent",
        "Skip Remediation",
        "Operator rejected service restart",
        output_data
    )
    return {
        **state,
        "report": state["report"] + [f"SkipAgent: {msg}"]
    }


# ─────────────────────────────────────────────
# Routing after human decision
# ─────────────────────────────────────────────
def route_after_approval(state: VMState) -> Literal["restart_process", "skip"]:
    return "restart_process" if state["human_approved"] else "skip"


# ─────────────────────────────────────────────
# Build the LangGraph
# ─────────────────────────────────────────────
def build_graph():
    builder = StateGraph(VMState)

    builder.add_node("servicenow",           agent_servicenow)
    builder.add_node("planner",              agent_planner)
    builder.add_node("ci_reachability",      agent_ci_reachability)
    builder.add_node("disk_health",          agent_disk_health)
    builder.add_node("memory_health",        agent_memory_health)
    builder.add_node("cpu_health",           agent_cpu_health)
    builder.add_node("process_check",        agent_process_check)
    builder.add_node("diagnostic_analyzer",  agent_diagnostic_analyzer)
    builder.add_node("human_approval",       agent_human_approval)
    builder.add_node("restart_process",      agent_restart_process)
    builder.add_node("skip",                 agent_skip)

    builder.set_entry_point("servicenow")
    builder.add_edge("servicenow",          "planner")
    builder.add_edge("planner",             "ci_reachability")
    builder.add_edge("ci_reachability",     "disk_health")
    builder.add_edge("disk_health",         "memory_health")
    builder.add_edge("memory_health",       "cpu_health")
    builder.add_edge("cpu_health",          "process_check")
    builder.add_edge("process_check",       "diagnostic_analyzer")
    builder.add_edge("diagnostic_analyzer", "human_approval")

    builder.add_conditional_edges(
        "human_approval",
        route_after_approval,
        {"restart_process": "restart_process", "skip": "skip"}
    )

    builder.add_edge("restart_process", END)
    builder.add_edge("skip",            END)

    checkpointer = MemorySaver()
    return builder.compile(checkpointer=checkpointer)


# ─────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────
def main():
    graph = build_graph()

    initial_state: VMState = {
        "vm_ip":                "",
        "snow_incident_id":     "",
        "snow_service":         "",
        "snow_state":           "",
        "plan":                 [],
        "plan_structured":      {},
        "reachable":            False,
        "disk_healthy":         False,
        "memory_ok":            False,
        "cpu_ok":               False,
        "process_state":        "",
        "process_pid":          0,
        "ci_details":           {},
        "connectivity_findings":{},
        "disk_findings":        {},
        "memory_findings":      {},
        "cpu_findings":         {},
        "process_findings":     {},
        "diagnosis":            {},
        "human_approved":       False,
        "report":               []
    }

    config = {"configurable": {"thread_id": "vm-stabilizer-1"}}

    print("\n" + "=" * 56)
    print("   VM STABILIZER – LangGraph Workflow")
    print("=" * 56)

    # ── Step 1: Run all agents until the human interrupt pauses the graph ──
    for event in graph.stream(initial_state, config=config, stream_mode="values"):
        pass

    # ── Step 2: Collect human decision ──
    print("\nEnter decision (approve / reject): ", end="")
    human_input = input().strip().lower()

    # ── Step 3: Resume graph from the interrupt point ──
    # stream_mode="updates" so the human_approval node does NOT re-execute its print block
    for event in graph.stream(
        Command(resume=human_input),
        config=config,
        stream_mode="updates"
    ):
        pass

    # ── Final Report ──
    final_state = graph.get_state(config).values
    print("\n" + "=" * 56)
    print("   FINAL REPORT")
    print("=" * 56)
    for line in final_state.get("report", []):
        print(f"  {line}")
    print("=" * 56)


if __name__ == "__main__":
    main()
